name: Docker Build and Push (Docker Compose)

on:
  push:
    branches: [ "master" ]

jobs:
  build-push:
    name: Build & Push from Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml build

      - name: Tag and Push Backend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kiii-project-v2:backend

      - name: Tag and Push Frontend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kiii-project-v2:frontend
